version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewTPPTestProject
  gitServerName: poanGit
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
- name: Default
  gitServerName: poanGit
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
